name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Conan Install
      run: |
        mkdir ${{github.workspace}}/build 
        cd ${{github.workspace}}/build
        conan install .. -b missing -s build_type=Release -s compiler.runtime=MT

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Conan Install
      run: |
        mkdir ${{github.workspace}}/build 
        cd ${{github.workspace}}/build
        conan install .. -b missing -s build_type=Release -s compiler.libcxx=libstdc++11

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      

#     - name: Test
#       working-directory: ${{github.workspace}}/build
#       run: ctest -C ${{env.BUILD_TYPE}}
      
