name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: MinSizeRel

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: windows-latest
            additional_conan_options: "-s compiler.runtime=MT"
          - os: ubuntu-latest
            additional_conan_options: "-s compiler.libcxx=libstdc++11"
          - os: macos-latest
            additional_conan_options: ""

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Conan Install
      run: |
        mkdir ${{ github.workspace }}/build 
        cd ${{ github.workspace }}/build
        conan install .. -b missing -s build_type=Release ${{ matrix.config.additional_conan_options }}

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#   - name: Test
#     working-directory: ${{github.workspace}}/build
#     run: ctest -C ${{env.BUILD_TYPE}}
      
